# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

variables:
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}: 
    releaseChannel: default
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}: 
    releaseChannel: staging

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g expo-cli    
  displayName: 'Build Frontend'
