stages:
    - stage: Test
      jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: |
            cd streaming-browser
            npm install
            npm test
          displayName: 'Backend Test'
        
          - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'BackendTestResults.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)/Tests'
            testRunTitle: 'Backend Test'
            displayName: 'Publishing Test Results'
        
    